version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: crypto_news_dev
    ports:
      - "8080:80"
    volumes:
      - ./uploads:/var/www/html/uploads:rw
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: crypto_news_db
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: crypto_news_db
      MYSQL_USER: crypto_user
      MYSQL_PASSWORD: crypto_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
