version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: crypto_news_dev
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
      - ./uploads:/var/www/html/uploads
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
